version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    ports:
    - 7474:7474
    - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment: 
      # Windows routing
      - NEO4J_dbms_connector_https_advertised__address=localhost:7473
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_connector_https_listen__address=0.0.0.0:7473
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687

      # Disable auth for now
      - NEO4J_dbms_security_auth__enabled=false

      